#!/usr/bin/env python3
"""Concatenate ``static/app/*.js`` fragments into ``static/app.js``.

The browser still loads a single classic script (IIFE). Edit the fragments
under ``src/housewire/ui/static/app/``, then run this script (or ``make bundle-ui``).
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_DIR = ROOT / "src" / "housewire" / "ui" / "static" / "app"
OUT = ROOT / "src" / "housewire" / "ui" / "static" / "app.js"

PARTS = [
    "01-core.js",
    "02-openings.js",
    "03-routing.js",
    "04-render.js",
    "05-shell.js",
]


def main() -> None:
    missing = [p for p in PARTS if not (APP_DIR / p).is_file()]
    if missing:
        raise SystemExit(f"missing fragments: {missing}")
    chunks: list[str] = []
    for name in PARTS:
        text = (APP_DIR / name).read_text()
        if not text.endswith("\n"):
            text += "\n"
        chunks.append(text)
    body = "\n" + "".join(chunks)
    banner = (
        "/* Generated by scripts/bundle_ui_app.py — do not edit directly.\n"
        " * Sources: src/housewire/ui/static/app/*.js\n"
        " */\n"
    )
    out = banner + "(() => {" + body + "})();\n"
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes) from {len(PARTS)} parts")


if __name__ == "__main__":
    main()
